const globalVars = [
    'BMap',

    'BMAP_AUTHENTIC_KEY',
    'BMap_loadScriptTime',
    'BMAP_API_VERSION',

    'BMAP_PANORAMA_POI_HOTEL',
    'BMAP_PANORAMA_POI_CATERING',
    'BMAP_PANORAMA_POI_MOVIE',
    'BMAP_PANORAMA_POI_TRANSI',
    'BMAP_PANORAMA_POI_INDOOR_SCENE',
    'BMAP_PANORAMA_POI_NONE',
    'BMAP_PANORAMA_INDOOR_SCENE',
    'BMAP_PANORAMA_STREET_SCENE',

    'BMAP_NORMAL_MAP',
    'BMAP_PERSPECTIVE_MAP',
    'BMAP_SATELLITE_MAP',
    'BMAP_HYBRID_MAP',

    'BMAP_ANIMATION_DROP',
    'BMAP_ANIMATION_BOUNCE',

    'BMAP_ANCHOR_TOP_LEFT',
    'BMAP_ANCHOR_TOP_RIGHT',
    'BMAP_ANCHOR_BOTTOM_LEFT',
    'BMAP_ANCHOR_BOTTOM_RIGHT',

    'BMAP_NAVIGATION_CONTROL_LARGE',
    'BMAP_NAVIGATION_CONTROL_SMALL',
    'BMAP_NAVIGATION_CONTROL_PAN',
    'BMAP_NAVIGATION_CONTROL_ZOOM',

    'BMAP_UNIT_METRIC',
    'BMAP_UNIT_IMPERIAL',

    'BMAP_MAPTYPE_CONTROL_HORIZONTAL',
    'BMAP_MAPTYPE_CONTROL_DROPDOWN',
    'BMAP_MAPTYPE_CONTROL_MAP',

    'BMAP_STATUS_SUCCESS',
    'BMAP_STATUS_CITY_LIST',
    'BMAP_STATUS_UNKNOWN_LOCATION',
    'BMAP_STATUS_UNKNOWN_ROUTE',
    'BMAP_STATUS_INVALID_KEY',
    'BMAP_STATUS_INVALID_REQUEST',
    'BMAP_STATUS_PERMISSION_DENIED',
    'BMAP_STATUS_SERVICE_UNAVAILABLE',
    'BMAP_STATUS_TIMEOUT',

    'BMAP_POI_TYPE_NORMAL',
    'BMAP_POI_TYPE_BUSSTOP',
    'BMAP_POI_TYPE_BUSLINE',
    'BMAP_POI_TYPE_SUBSTOP',
    'BMAP_POI_TYPE_SUBLINE',

    'BMAP_TRANSIT_POLICY_LEAST_TIME',
    'BMAP_TRANSIT_POLICY_LEAST_TRANSFER',
    'BMAP_TRANSIT_POLICY_LEAST_WALKING',
    'BMAP_TRANSIT_POLICY_AVOID_SUBWAYS',
    'BMAP_LINE_TYPE_BUS',
    'BMAP_LINE_TYPE_SUBWAY',
    'BMAP_LINE_TYPE_FERRY',

    'BMAP_DRIVING_POLICY_LEAST_TIME',
    'BMAP_DRIVING_POLICY_LEAST_DISTANCE',
    'BMAP_DRIVING_POLICY_AVOID_HIGHWAYS',

    'BMAP_MODE_DRIVING',
    'BMAP_MODE_TRANSIT',
    'BMAP_MODE_WALKING',
    'BMAP_MODE_NAVIGATION',

    'BMAP_HIGHLIGHT_STEP',
    'BMAP_HIGHLIGHT_ROUTE',
    'BMAP_ROUTE_TYPE_DRIVING',
    'BMAP_ROUTE_TYPE_WALKING',
    'BMAP_ROUTE_STATUS_NORMAL',
    'BMAP_ROUTE_STATUS_EMPTY',
    'BMAP_ROUTE_STATUS_ADDRESS',

    'BMAP_POINT_DENSITY_HIGH',
    'BMAP_POINT_DENSITY_MEDIUM',
    'BMAP_POINT_DENSITY_LOW',

    'BMAP_POINT_SHAPE_STAR',
    'BMAP_POINT_SHAPE_WATERDROP',
    'BMAP_POINT_SHAPE_CIRCLE',
    'BMAP_POINT_SHAPE_SQUARE',
    'BMAP_POINT_SHAPE_RHOMBUS',

    'BMAP_POINT_SIZE_TINY',
    'BMAP_POINT_SIZE_SMALLER',
    'BMAP_POINT_SIZE_SMALL',
    'BMAP_POINT_SIZE_NORMAL',
    'BMAP_POINT_SIZE_BIG',
    'BMAP_POINT_SIZE_BIGGER',
    'BMAP_POINT_SIZE_HUGE',

    'BMap_Symbol_SHAPE_CAMERA',
    'BMap_Symbol_SHAPE_WARNING',
    'BMap_Symbol_SHAPE_SMILE',
    'BMap_Symbol_SHAPE_CLOCK',
    'BMap_Symbol_SHAPE_POINT',
    'BMap_Symbol_SHAPE_PLANE',
    'BMap_Symbol_SHAPE_CIRCLE',
    'BMap_Symbol_SHAPE_RECTANGLE',
    'BMap_Symbol_SHAPE_RHOMBUS',
    'BMap_Symbol_SHAPE_STAR',
    'BMap_Symbol_SHAPE_BACKWARD_CLOSED_ARROW',
    'BMap_Symbol_SHAPE_FORWARD_CLOSED_ARROW',
    'BMap_Symbol_SHAPE_BACKWARD_OPEN_ARROW',
    'BMap_Symbol_SHAPE_FORWARD_OPEN_ARROW',

    'BMAP_CONTEXT_MENU_ICON_ZOOMIN',
    'BMAP_CONTEXT_MENU_ICON_ZOOMOUT',

    'BMAP_SYS_DRAWER',
    'BMAP_SVG_DRAWER',
    'BMAP_VML_DRAWER',
    'BMAP_CANVAS_DRAWER',
    'BMAP_SVG_DRAWER_FIRST'
];

const globals = {};
globalVars.forEach(function(value) {
    globals[value] = true;
});

module.exports = globals;
